# Generated by Django 5.1.7 on 2025-04-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('zapi_url_text', models.URLField()),
                ('zapi_url_audio', models.URLField()),
                ('zapi_token', models.CharField(max_length=255)),
                ('assistant_id', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.clientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('grau_interesse', models.CharField(choices=[('baixo', 'Baixo'), ('médio', 'Médio'), ('alto', 'Alto')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.clientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviado_por', models.CharField(choices=[('gessie', 'Gessie'), ('pessoa', 'Pessoa')], max_length=10)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('áudio', 'Áudio')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('profissional', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.clientconfig')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
            ],
        ),
    ]
