# Generated by Django 5.1.7 on 2025-04-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.clientuser'),
        ),
        migrations.AlterField(
            model_name='message',
            name='enviado_por',
            field=models.CharField(choices=[('gessie', 'Gessie'), ('pessoa', 'Pessoa'), ('usuario', 'Usuário')], max_length=10),
        ),
    ]
