# Generated by Django 5.1.7 on 2025-04-19 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_message_client_user_alter_message_enviado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.person'),
        ),
    ]
