# Generated by Django 5.1.7 on 2025-04-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_person_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.clientuser'),
        ),
    ]
