# Generated by Django 5.1.7 on 2025-04-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_appointment_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_recebidos', to='bot.clientuser'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='profissional',
            field=models.CharField(default='Profissional não informado', max_length=255),
            preserve_default=False,
        ),
    ]
