# Generated by Django 5.1.7 on 2025-04-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_appointment_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='idade',
            field=models.CharField(default='indefinida', max_length=255),
            preserve_default=False,
        ),
    ]
