# Generated by Django 5.1.7 on 2025-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_person_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grau_interesse',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('médio', 'Médio'), ('alto', 'Alto')], max_length=50, null=True),
        ),
    ]
