# Generated by Django 5.1.7 on 2025-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_appointment_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='bot.especialidade'),
        ),
    ]
