# Generated by Django 5.1.7 on 2025-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_especialidade_clientuser_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconfig',
            name='regras_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
