# Generated by Django 5.1.7 on 2025-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilencioTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('ate', models.DateTimeField()),
            ],
        ),
    ]
