# Generated by Django 5.1.7 on 2025-05-08 15:53

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_silenciotemporario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-ativo', 'nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='clientuser',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto local do contato', null=True, storage=django.core.files.storage.FileSystemStorage(location='fotos'), upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='bot.clientconfig'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', message='CPF deve conter 11 dígitos numéricos', regex='^[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='idade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas_responsaveis', to='bot.clientuser'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
