# Generated by Django 5.1.7 on 2025-05-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_alter_person_options_clientuser_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.clientconfig'),
            preserve_default=False,
        ),
    ]
