# Generated by Django 5.1.7 on 2025-05-14 22:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_conversation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto local do contato', null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/softdotpro/gessievirtual/media/fotos'), upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
