# Generated by Django 5.1.7 on 2025-05-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_conversation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='bot.clientconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='especialidade',
            unique_together={('nome', 'client')},
        ),
    ]
