# Generated by Django 5.1.7 on 2025-06-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_especialidade_client_alter_especialidade_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_endereco', models.TextField()),
                ('cliente_contato', models.CharField(max_length=100)),
                ('descricao_servico', models.TextField()),
                ('materiais_equipamentos', models.TextField(blank=True)),
                ('tempo_estimado', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.clientconfig')),
                ('profissional_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.clientuser')),
            ],
        ),
    ]
