# Generated by Django 5.1.7 on 2025-06-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_alter_appointment_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeDeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='bot.clientconfig')),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='bot.unidadedeatendimento'),
        ),
    ]
